inpath

diff --git a/inpath b/inpath
--- a/inpath
+++ b/inpath
@@ -36,3 +36,16 @@ checkForCmdInPath()
     fi
   fi
 }
+
+if [ $# -ne 1 ] ; then
+	echo "Usage: $0 command" >&2; exit 1
+fi
+
+checkForCmdInPath "$1"
+	case $? in
+		0 ) echo "$1 found in PATH"		;;
+		1 ) echo "$1 not found in PATH"		;;
+		2 ) echo "$1 not found in PATH"		;;
+	esac
+
+exit 0
